name: Bug report
description: Report a reproducible bug or regression
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: What happened?
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: 1. ...
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Environment
      placeholder: OS, Python version, etc.
